name: Build on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      - run: git config user.name 'sebkolind'
      - run: git config user.email 'sks1993@gmail.com'
      - run: git add . && git commit -m 'deploy'
